# Generated by Django 5.2.8 on 2025-11-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='tech',
            new_name='email',
        ),
        migrations.AddField(
            model_name='developer',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='developer/image/'),
        ),
    ]
