# Generated by Django 5.2.8 on 2025-11-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='work/thumbnails/'),
        ),
        migrations.AddField(
            model_name='work',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='work/videos/'),
        ),
    ]
