# Generated by Django 5.2.8 on 2026-04-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0004_alter_work_thumbnail_alter_work_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
        migrations.AlterField(
            model_name="work",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
